#!/usr/bin/env python3
"""
Execute the ccapi smoke suite using the canonical requests provided in the
documentation. The script checks schema, header and transaction metadata plus
the main CRUD operations implemented by cc-tools.
"""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Tuple
from urllib import error, request


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run smoke tests against the ccapi gateway.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--base-url", default="http://localhost:8085/api", help="Gateway base URL.")
    parser.add_argument("--channel", default="stcs-channel", help="Fabric channel.")
    parser.add_argument("--chaincode", default="stcs-cc", help="Chaincode name.")
    parser.add_argument("--token", help="JWT token for authorization.")
    parser.add_argument("--org", help="Optional organization override (?org=<org>).")
    parser.add_argument(
        "--manifest",
        default="marketplace/stcs-channel__stcs-cc.json",
        help="Path to the manifest generated by marketplace_sync.py (used for validation).",
    )
    parser.add_argument(
        "--patient-key",
        default="patient:387c97eb-cf0b-5cdb-96d3-38d8408922bc",
        help="Patient asset key used by readAsset and readAssetHistory tests.",
    )
    parser.add_argument(
        "--search-limit",
        type=int,
        default=2,
        help="Limit parameter for the Search test.",
    )
    parser.add_argument(
        "--create-num-protocolo",
        default="123",
        help="Protocol number used in the CreateAsset (exam) test.",
    )
    parser.add_argument(
        "--update-num-protocolo",
        default="11856",
        help="Protocol number used in the UpdateAsset (exam) test.",
    )
    parser.add_argument(
        "--doctor-hash",
        default="doctor:bd2f37f3-00e8-5ebc-aa98-652bef83858fd",
        help="Doctor hash for the UpdateAsset test.",
    )
    parser.add_argument(
        "--patient-hash",
        default="patient:9d6f96f4-e796-5a56-a010-06812033b03bd",
        help="Patient hash for the UpdateAsset test.",
    )
    parser.add_argument(
        "--delete-asset-ref",
        default="exam::11856",
        help="Asset reference used in the DeleteAsset test.",
    )
    parser.add_argument(
        "--skip-mutations",
        action="store_true",
        help="Skip create/update/delete smoke tests (read-only validation only).",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=20,
        help="Timeout in seconds for HTTP requests.",
    )
    return parser.parse_args()


def load_manifest(path: str) -> Dict[str, Any]:
    try:
        with open(path, "r", encoding="utf-8") as fp:
            return json.load(fp)
    except FileNotFoundError as exc:
        raise SystemExit(f"Manifest not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Manifest {path} is not valid JSON: {exc}") from exc


def make_headers(token: Optional[str]) -> Dict[str, str]:
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"JWT {token}"
    headers["cache-control"] = "no-cache"
    headers["Accept"] = "application/json, text/plain, */*"
    headers["User-Agent"] = "ccapi-smoke-test/1.0"
    return headers


def http_call(
    method: str,
    url: str,
    *,
    headers: Dict[str, str],
    body: Optional[Dict[str, Any]] = None,
    timeout: int = 20,
) -> Any:
    data: Optional[bytes]
    if body is None:
        data = None
    elif isinstance(body, (bytes, bytearray)):
        data = body
    elif body == "":
        data = b""
    else:
        data = json.dumps(body).encode("utf-8")

    req = request.Request(url=url, method=method.upper(), data=data)
    for key, value in headers.items():
        req.add_header(key, value)

    try:
        with request.urlopen(req, timeout=timeout) as resp:
            payload = resp.read().decode("utf-8")
    except error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "ignore")
        raise RuntimeError(f"{method} {url} -> HTTP {exc.code}: {detail}") from exc
    except error.URLError as exc:
        raise RuntimeError(f"{method} {url} failed: {exc.reason}") from exc

    if not payload:
        return None
    try:
        return json.loads(payload)
    except json.JSONDecodeError:
        return payload


def ensure_keys(container: Dict[str, Any], keys: Dict[str, type], context: str) -> None:
    for key, expected_type in keys.items():
        if key not in container:
            raise AssertionError(f"{context}: missing key '{key}'")
        if not isinstance(container[key], expected_type):
            raise AssertionError(
                f"{context}: key '{key}' expected {expected_type.__name__}, "
                f"got {type(container[key]).__name__}"
            )


class SkipTest(Exception):
    """Signal that a smoke test should be skipped (environmental constraint)."""


@dataclass
class SmokeTest:
    name: str
    method: str
    path: str
    body: Any
    validator: Callable[[Any, Dict[str, Any]], None]
    skip_when_mutation_disabled: bool = False
    payload_builder: Optional[Callable[[Dict[str, Any]], Any]] = None
    on_success: Optional[Callable[[Any, Dict[str, Any]], None]] = None
    on_error: Optional[Callable[[Exception, Dict[str, Any]], Optional[str]]] = None

    def run(
        self,
        *,
        base_prefix: str,
        headers: Dict[str, str],
        org: Optional[str],
        timeout: int,
        context: Dict[str, Any],
    ) -> None:
        query_suffix = f"?org={org}" if org else ""
        url = f"{base_prefix}{self.path}{query_suffix}"
        try:
            payload: Any
            if self.payload_builder:
                payload = self.payload_builder(context)
            else:
                payload = self.body
        except SkipTest as exc:
            raise exc

        try:
            response = http_call(
                self.method,
                url,
                headers=headers,
                body=payload,
                timeout=timeout,
            )
        except Exception as exc:  # pylint: disable=broad-except
            if self.on_error:
                skip_message = self.on_error(exc, context)
                if skip_message:
                    raise SkipTest(skip_message) from exc
            raise

        self.validator(response, context)
        if self.on_success:
            self.on_success(response, context)


def build_tests(args: argparse.Namespace, manifest: Dict[str, Any]) -> List[Tuple[str, SmokeTest]]:
    assets = [asset["tag"] for asset in manifest.get("assets", []) if "tag" in asset]
    txs = [tx["tag"] for tx in manifest.get("transactions", []) if "tag" in tx]
    tests: List[Tuple[str, SmokeTest]] = []
    create_proto = f"{args.create_num_protocolo}-{uuid.uuid4().hex[:8]}"

    def schema_validator(response: Any, _context: Dict[str, Any]) -> None:
        if not isinstance(response, list):
            raise AssertionError("getSchema should return an array")
        response_tags = {item.get("tag") for item in response if isinstance(item, dict)}
        missing = [tag for tag in assets if tag not in response_tags]
        if missing:
            raise AssertionError(f"getSchema missing asset tags: {', '.join(missing)}")

    def header_validator(response: Any, _context: Dict[str, Any]) -> None:
        if not isinstance(response, dict):
            raise AssertionError("getHeader must return an object")
        ensure_keys(
            response,
            {"name": str, "version": str, "ccToolsVersion": str, "orgMSP": str},
            "getHeader",
        )

    def tx_validator_factory(tag: str) -> Callable[[Any, Dict[str, Any]], None]:
        def _validator(response: Any, _context: Dict[str, Any]) -> None:
            if not isinstance(response, dict):
                raise AssertionError(f"getTx({tag}) must return an object")
            if response.get("tag") != tag:
                raise AssertionError(f"getTx({tag}) -> unexpected tag {response.get('tag')}")
            ensure_keys(
                response,
                {"args": list, "method": str, "metaTx": bool, "readOnly": bool},
                f"getTx({tag})",
            )

        return _validator

    def search_validator(response: Any, _context: Dict[str, Any]) -> None:
        if not isinstance(response, dict):
            raise AssertionError("search must return an object")
        ensure_keys(response, {"metadata": dict, "result": list}, "search")

    def search_error_handler(exc: Exception, _context: Dict[str, Any]) -> Optional[str]:
        message = str(exc)
        if "ExecuteQueryWithMetadata not supported for leveldb" in message:
            return "Rich queries unavailable (LevelDB backend)"
        return None

    def read_asset_validator(response: Any, _context: Dict[str, Any]) -> None:
        if not isinstance(response, dict):
            raise AssertionError("readAsset must return an object")
        ensure_keys(response, {"@assetType": str, "@key": str}, "readAsset")

    def read_error_handler(exc: Exception, _context: Dict[str, Any]) -> Optional[str]:
        message = str(exc).lower()
        if "asset not found" in message:
            return "No exam asset available to read"
        return None

    def history_validator(response: Any, _context: Dict[str, Any]) -> None:
        if not isinstance(response, list):
            raise AssertionError("readAssetHistory must return an array")

    def history_error_handler(exc: Exception, _context: Dict[str, Any]) -> Optional[str]:
        message = str(exc).lower()
        if "history not found" in message:
            return "No history available for exam asset"
        return None

    def mutation_validator_factory(name: str) -> Callable[[Any, Dict[str, Any]], None]:
        def _validator(response: Any, _context: Dict[str, Any]) -> None:
            if isinstance(response, dict) and response.get("error"):
                raise AssertionError(f"{name} failed: {response.get('error')}")

        return _validator

    tests.append(
        (
            "getSchema",
            SmokeTest(
                name="getSchema",
                method="POST",
                path="/query/getSchema",
                body={},
                validator=schema_validator,
            ),
        )
    )
    tests.append(
        (
            "getHeader",
            SmokeTest(
                name="getHeader",
                method="POST",
                path="/query/getHeader/",
                body={},
                validator=header_validator,
            ),
        )
    )
    tests.append(
        (
            "searchPatients",
            SmokeTest(
                name="searchPatients",
                method="POST",
                path="/query/search",
                body={
                    "query": {
                        "selector": {"@assetType": "patient"},
                        "limit": args.search_limit,
                        "bookmark": "",
                    },
                    "resolve": True,
                },
                validator=search_validator,
                on_error=search_error_handler,
            ),
        )
    )

    def ensure_exam_key(context: Dict[str, Any]) -> Tuple[str, str, str]:
        key = context.get("exam_key")
        asset_type = context.get("exam_assetType")
        num_protocolo = context.get("exam_numProtocolo")
        if not key or not asset_type or not num_protocolo:
            raise SkipTest("Exam asset not created in this session")
        return key, asset_type, num_protocolo

    def read_exam_payload(context: Dict[str, Any]) -> Dict[str, Any]:
        _key, asset_type, num_protocolo = ensure_exam_key(context)
        return {
            "key": {
                "@assetType": asset_type,
                "numProtocolo": num_protocolo,
            },
            "resolve": True,
        }

    tests.append(
        (
            "readExam",
            SmokeTest(
                name="readExam",
                method="POST",
                path="/query/readAsset",
                body=None,
                payload_builder=read_exam_payload,
                validator=read_asset_validator,
                on_error=read_error_handler,
            ),
        )
    )

    def history_exam_payload(context: Dict[str, Any]) -> Dict[str, Any]:
        _key, asset_type, num_protocolo = ensure_exam_key(context)
        return {
            "key": {
                "@assetType": asset_type,
                "numProtocolo": num_protocolo,
            },
            "resolve": True,
        }

    tests.append(
        (
            "readExamHistory",
            SmokeTest(
                name="readExamHistory",
                method="POST",
                path="/query/readAssetHistory",
                body=None,
                payload_builder=history_exam_payload,
                validator=history_validator,
                on_error=history_error_handler,
            ),
        )
    )

    for tag in txs:
        tests.append(
            (
                f"getTx::{tag}",
                SmokeTest(
                    name=f"getTx::{tag}",
                    method="POST",
                    path="/query/getTx",
                    body={"txName": tag},
                    validator=tx_validator_factory(tag),
                ),
            )
        )

    if not args.skip_mutations:
        def store_exam_key(response: Any, context: Dict[str, Any]) -> None:
            candidate = response
            if isinstance(candidate, dict) and "result" in candidate:
                candidate = candidate["result"]
            key = None
            asset_type = None
            if isinstance(candidate, dict):
                key = candidate.get("@key")
                asset_type = candidate.get("@assetType")
            elif isinstance(candidate, list):
                for item in candidate:
                    if isinstance(item, dict) and "@key" in item:
                        key = item["@key"]
                        asset_type = item.get("@assetType")
                        break
            if not key:
                key = f"exam:{create_proto}"
            if not asset_type:
                asset_type = key.split(":", 1)[0] if ":" in key else "exam"
            context["exam_key"] = key
            context["exam_numProtocolo"] = create_proto
            context["exam_assetType"] = asset_type

        def update_exam_payload(context: Dict[str, Any]) -> Dict[str, Any]:
            _key, asset_type, num_protocolo = ensure_exam_key(context)
            return {
                "update": {
                    "@assetType": asset_type,
                    "numProtocolo": num_protocolo,
                    "name": "Exame de Pupilometria Atualizado",
                    "diagnosisHash": "diagnosis_hash_updated",
                    "treatmentHash": "treatment_hash_updated",
                    "isGlaucomaIA": False,
                    "isReady": False,
                }
            }

        def delete_exam_payload(context: Dict[str, Any]) -> Dict[str, Any]:
            _key, asset_type, num_protocolo = ensure_exam_key(context)
            return {
                "key": {
                    "@assetType": asset_type,
                    "numProtocolo": num_protocolo,
                }
            }

        def deletion_error_handler(exc: Exception, _context: Dict[str, Any]) -> Optional[str]:
            message = str(exc).lower()
            if "tx named deleteasset does not exist" in message:
                return "deleteAsset meta transaction unavailable in this deployment"
            return None

        def random_hash() -> str:
            return uuid.uuid4().hex + uuid.uuid4().hex

        def create_exam_payload(_context: Dict[str, Any]) -> Dict[str, Any]:
            base_url = "https://example.com/resources"
            return {
                "asset": [
                    {
                        "@assetType": "exam",
                        "numProtocolo": create_proto,
                        "initialDoctorHash": random_hash(),
                        "patientHash": random_hash(),
                        "timestamp": "2025-10-24T03:00:00.000Z",
                        "name": f"Exame Automático {create_proto}",
                        "urlPupilometerVideo": f"{base_url}/{create_proto}/pupilometer.mp4",
                        "filePupilometerVideoMetadataHash": random_hash(),
                        "urlAiCurves": f"{base_url}/{create_proto}/curvas.csv",
                        "fileAiCurvesMetadataHash": random_hash(),
                        "urlImageChart": f"{base_url}/{create_proto}/grafico.jpg",
                        "fileImageChartMetadataHash": random_hash(),
                        "diagnosisHash": random_hash(),
                        "treatmentHash": random_hash(),
                        "isGlaucomaIA": True,
                        "isReady": True,
                    }
                ]
            }

        tests.extend(
            [
                (
                    "createExam",
                    SmokeTest(
                        name="createExam",
                        method="POST",
                        path="/invoke/createAsset",
                        body=None,
                        payload_builder=create_exam_payload,
                        validator=mutation_validator_factory("createExam"),
                        on_success=store_exam_key,
                        skip_when_mutation_disabled=False,
                    ),
                ),
                (
                    "updateExam",
                    SmokeTest(
                        name="updateExam",
                        method="PUT",
                        path="/invoke/updateAsset",
                        body=None,
                        payload_builder=update_exam_payload,
                        validator=mutation_validator_factory("updateExam"),
                        skip_when_mutation_disabled=True,
                    ),
                ),
                (
                    "deleteExam",
                    SmokeTest(
                        name="deleteExam",
                        method="DELETE",
                        path="/invoke/deleteAsset",
                        body=None,
                        payload_builder=delete_exam_payload,
                        validator=mutation_validator_factory("deleteExam"),
                        on_error=deletion_error_handler,
                        skip_when_mutation_disabled=True,
                    ),
                ),
            ]
        )

    return tests


def main() -> None:
    args = parse_args()
    manifest = load_manifest(args.manifest)
    tests = build_tests(args, manifest)
    headers = make_headers(args.token)

    base_prefix = f"{args.base_url}/{args.channel}/{args.chaincode}"
    failures: Dict[str, str] = {}
    skips: Dict[str, str] = {}
    context: Dict[str, Any] = {}

    for name, test in tests:
        if args.skip_mutations and test.skip_when_mutation_disabled:
            continue
        try:
            test.run(
                base_prefix=base_prefix,
                headers=headers,
                org=args.org,
                timeout=args.timeout,
                context=context,
            )
            print(f"[OK] {name}")
        except SkipTest as exc:
            skips[name] = str(exc)
            print(f"[SKIP] {name}: {exc}")
        except Exception as exc:  # pylint: disable=broad-except
            failures[name] = str(exc)
            print(f"[FAIL] {name}: {exc}")

    if failures:
        details = "\n".join([f" - {name}: {error_msg}" for name, error_msg in failures.items()])
        raise SystemExit(f"\n{len(failures)} smoke test(s) failed:\n{details}")

    if skips:
        for name, reason in skips.items():
            print(f"(info) {name} skipped: {reason}")

    executed = len([1 for name, test in tests if not (args.skip_mutations and test.skip_when_mutation_disabled)])
    print(f"\nCompleted {executed} smoke tests ({len(skips)} skipped).")


if __name__ == "__main__":
    main()
