# Generated by Django 4.2.16 on 2025-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_node_admin_cert_node_admin_key_alter_fabricca_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(help_text='Nível do evento (info, warning, error)', max_length=16)),
                ('message', models.TextField(help_text='Mensagem do evento')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='network',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='node',
            name='created_at',
        ),
    ]
