# Generated by Django 4.2.16 on 2025-10-26 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventlog_alter_agent_options_alter_network_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Create time of network'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Create time of node'),
            preserve_default=False,
        ),
    ]
